# Generated by Django 5.1 on 2024-08-31 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descriptio',
            new_name='description',
        ),
    ]
